### ISSUE TITLE
Faceted Browse pages

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-themes/lively#10]
http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-omeka-s-site/faceted-browse/2

1) On a faceted-browse page like the above, items show up in a table. Can we get rid of the bottom dotted border on the last item in the table?

<img width="1058" alt="Screenshot 2024-06-03 at 14 11 42" src="https://github.com/omeka-s-themes/lively/assets/28012148/2152ceee-89d6-4efe-ba20-782983681b1f">

2) The sorting dropdowns are doing the same cutoff here I already mentioned:

<img width="566" alt="Screenshot 2024-06-03 at 14 14 07" src="https://github.com/omeka-s-themes/lively/assets/28012148/4217340f-ad4c-4692-9ef1-228e1c3e9b32">

3) The "Instructions" button in the left sidebar doesn't work in this theme. 

4) Would you also consider a mouseover link change? When things like subject headings display like this it can be hard to know which one you're about to click on. A bullet list might be a good solution. 

Otherwise I think these pages look really good already! 

5) We do have a new FB page block that should be styled the same (basically just the header bar needs doing, and the bold):

http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-omeka-s-site/page/fb-test

**Comment by nelsonamaya82** [comment]
@allanaaa all issues were fixed and pushed to the Master banch of the theme. Please let me know if it works.

**Comment by allanaaa** [comment]
Looks great!
