### ISSUE TITLE
Map Browse page

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-themes/lively#12]
Something odd on the Map Browse page added by the Mapping module, which only seems to be happening in this theme:

http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-second-site/map-browse

The line with "0 results" appearing after the map, before the search fields, shouldn't be there. 

Compare to http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-fourth-site/map-browse and http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-third-site/map-browse if that helps.

**Comment by allanaaa** [comment]
Sorry, I think my development version of the Mapping module is causing some untoward stuff here. 

For one, looks like @jimsafley changed the URL of the Map Browse page. It's now http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-second-site/mapping/index/browse

And (in this theme only) the map isn't appearing. Still getting 0 results but with an error at the bottom: 

> Notice: Undefined variable: features in /var/www/html/amayer/amayer-s/omeka-s/themes/lively/view/mapping/site/index/browse.phtml on line 40
> 
> Warning: Invalid argument supplied for foreach() in /var/www/html/amayer/amayer-s/omeka-s/themes/lively/view/mapping/site/index/browse.phtml on line 40

Comparison pages are now http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-third-site/mapping/index/browse and http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-fourth-site/mapping/index/browse

If we should hold off on this until the new Mapping version is released, @jimsafley, just let us know. I don't know if this is an easy fix or not.

**Comment by nelsonamaya82** [comment]
@allanaaa I adjusted some styling in order to avoid overwriting the Mapping's default browse page. Now it should work as expected based on the module's code/template, still preserving the Lively style.

**Comment by allanaaa** [comment]
These issues are now fixed. 

http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-second-site/mapping/index/browse

<img width="932" alt="Screenshot 2024-11-18 at 10 03 28" src="https://github.com/user-attachments/assets/59cea990-1891-47b2-84fb-9aae893c0aea">


The "Search Map" button at the bottom isn't quite in line with the theme style, e.g. on the advanced search page, but if this is a technical restriction I think it looks fine and this can be closed.

**Comment by nelsonamaya82** [comment]
@allanaaa I pushed an adjustment to align the Search button to the right so it looks more in line with the theme style. I cannot make it floating as in the Advanced Search as I'd need to overwrite the module.

**Comment by allanaaa** [comment]
Looks good to me!
