### ISSUE TITLE
"Part of" showing on all item pages; "Attachment link type" setting not working

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-themes/lively#13]
I've noticed that when you're looking at an item:

http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-second-site/item/3620#lg=1&slide=0

There is a line at the bottom of the page indicating that the item is part of ... itself. 

<img width="1014" alt="Screenshot 2024-10-18 at 15 26 35" src="https://github.com/user-attachments/assets/02486a72-a11b-4946-ad5f-25c01602e165">

I think this line is only supposed to show on media pages?

... So when I tried to view a media page, it gave me a "Direct link to file" behaviour, even though the site setting is on "Media page":

<img width="847" alt="Screenshot 2024-10-18 at 15 24 07" src="https://github.com/user-attachments/assets/58ad7db8-1292-4d3e-b90d-18675c45eac2">

This setting works on other sites in the same installation, so I'm supposing this is a theme issue.

**Comment by nelsonamaya82** [comment]
@allanaaa thanks, I removed "Part of" from all item pages and fixed a styling issue on headings I saw on the example you attached.

However I tested the different "Attachment link type" options on a media block and it works as expected, could you send me more details on where did you test it?

**Comment by allanaaa** [comment]
Yep, that second one was my mistake! I had the "Media embeds" block in the right bar, which naturally opens the full-size media itself; it looks much the same as the "Media list" block when in a narrower sidebar.
