### ISSUE TITLE
Item with metadata does not wrap content when floated

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-themes/lively#2]
<img width="1080" alt="image" src="https://github.com/omeka-s-themes/lively/assets/606764/1a6a3b47-ec6b-4413-9518-27e23bbd3cb3">

#1

**Comment by nelsonamaya82** [comment]
@kimisgold Do you have a live example on any URL that I can visit? or Could you guide me on how did you build the example above?

**Comment by kimisgold** [comment]
This was my mistake, as I was testing it against new features.
