### ISSUE TITLE
Grid containers behave inconsistently

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-themes/lively#4]
<img width="1308" alt="image" src="https://github.com/omeka-s-themes/lively/assets/606764/71814677-64cf-4963-9b0b-2749966ef93e">

I've noticed that thumbnails can break out of containers, and some containers can flow behind others. Margins between containers can also vary.

#1

**Comment by kimisgold** [comment]
http://dev.omeka.org/knguyen/omeka-s/s/test/item 

I'm seeing these behaviors on all my macos browsers: Chrome, Firefox, Safari.

**Comment by nelsonamaya82** [comment]
@kimisgold I pushed a fix to the [master branch](https://github.com/omeka-s-themes/lively), could you pull the latest code and test again? Please let me know if it works for you so I replicate the adjustments in Freedom S.

**Comment by kimisgold** [comment]
Everything looks great.
