### ISSUE TITLE
Linked resource titles can wrap awkwardly on show views

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-themes/lively#5]
<img width="1434" alt="image" src="https://github.com/omeka-s-themes/lively/assets/606764/d3669a8c-e294-4043-830f-cc087c8a7308">

This happens when linked resources is placed into a sidebar or generally narrower content region.

#1

**Comment by nelsonamaya82** [comment]
@kimisgold thanks for catching this bug, it's fixed now in the [master](https://github.com/omeka-s-themes/lively) branch.
<img width="1436" alt="image" src="https://github.com/omeka-s-themes/lively/assets/6953921/621c2616-fb0d-4798-a6af-1d91294aec02">
