### ISSUE TITLE
Misc

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-themes/lively#8]
Re https://github.com/omeka-s-themes/lively/issues/1

1) I don't think we need an arrow next to menu content that doesn't have any sub-items:

<img width="394" alt="Screenshot 2024-06-03 at 13 03 14" src="https://github.com/omeka-s-themes/lively/assets/28012148/dc2ad906-6209-4a41-a0a9-68fb5b6fe4a2">

If you want to keep the arrows for style, I would move them to before the text - in line with your list styles (see below) and to keep people from thinking they will expand and collapse the way arrows do in other Omeka themes. 

2) Your left-hand pink title decoration doesn't always respect the height of the title container:

<img width="596" alt="Screenshot 2024-06-03 at 13 07 48" src="https://github.com/omeka-s-themes/lively/assets/28012148/36dc11a5-322d-4f34-b5db-dd5fa5df7c32">
<img width="879" alt="Screenshot 2024-06-03 at 13 08 56" src="https://github.com/omeka-s-themes/lively/assets/28012148/cbf1155a-3f27-4236-bbd1-c6cac8ff27bc">

3) Your list styles are a bit different (here is the TOC page block below the new Item Hierarchy block), not sure why:

<img width="584" alt="Screenshot 2024-06-03 at 13 10 44" src="https://github.com/omeka-s-themes/lively/assets/28012148/d1bc0541-a8ef-44f1-93e8-cf2c3f63ea22">

In the code, one is being modified with ::marker and the other isn't - not sure if this is something the new module needs to refer to, or if your theme should be covering all list instances:

<img width="860" alt="Screenshot 2024-06-03 at 13 13 55" src="https://github.com/omeka-s-themes/lively/assets/28012148/0725f4de-ba23-4016-a75b-0b79a7cc98b6">

4) The sorting buttons on the item set browse page should be longer instead of cutting off text:

<img width="541" alt="Screenshot 2024-06-03 at 13 16 58" src="https://github.com/omeka-s-themes/lively/assets/28012148/d9947823-a3a3-40cb-b71f-e94445237eab">

They look fine on item browse:

<img width="691" alt="Screenshot 2024-06-03 at 13 18 01" src="https://github.com/omeka-s-themes/lively/assets/28012148/45f33ce2-d5fc-4119-814b-dbd5daa4bc3e">

5) I wouldn't have two Advanced Search links so close by each other, seems redundant. It doesn't appear that I have the option to hide that, or to hide the top bar when empty. 

<img width="506" alt="Screenshot 2024-06-03 at 13 19 24" src="https://github.com/omeka-s-themes/lively/assets/28012148/6a01425e-21ac-4493-9bee-69d92e71a04b">

6) The map pin suggests to me this is a link to a map coordinate - any way to add links to that contact field? The other two work fine, though I want help text in the admin side to say that they will become live links.

<img width="638" alt="Screenshot 2024-06-03 at 13 20 23" src="https://github.com/omeka-s-themes/lively/assets/28012148/41637c13-9779-4b04-92e6-ff534b7b112d">

**Comment by allanaaa** [comment]
7. In media blocks, the title below the media sits underneath the decorative border. I'm not a fan of it sitting on top of the content either - it should match the other tiles IMO.
<img width="601" alt="Screenshot 2024-06-03 at 13 27 01" src="https://github.com/omeka-s-themes/lively/assets/28012148/cf0e6042-b073-47ec-b2e5-0a35a47d9b80">
<img width="1451" alt="Screenshot 2024-06-03 at 13 28 19" src="https://github.com/omeka-s-themes/lively/assets/28012148/b9c3e0e3-101e-4f91-8611-8dac249abd92">

8. What determines whether an image flows past its container? Any way to turn that off? I'm not a fan of it happening sometimes but not all the time. 
<img width="989" alt="Screenshot 2024-06-03 at 13 28 38" src="https://github.com/omeka-s-themes/lively/assets/28012148/4f557814-8d1d-4448-b5a3-9a3de7a23ef6">

**Comment by allanaaa** [comment]
9. I have issues with resource regions in this theme. The "Main" region is not significantly wider than the "left sidebar" and "right sidebar" at full browser widths, and you don't even really see that layout unless you're at 1200px or wider, right? And then from 1440px up you don't expand the main region any more, just add whitespace on either side. Sort of hard to use our blocks to their fullest potential. I mean lightbox gallery, map, media render - basically any site with decent graphics is not going to want 3 columns, and any site that's only text may not want 3 columns either, because that's just busy.
10. Does it need to be a 1-column layout when narrowed? Or can it go down to 2 columns first? 
11. Can we rename the regions, "Center" instead of "Main"? 
12. I would also put some help text somewhere to indicate that it'll be Main, then Left, then Right, when the browser is any narrower than 1200px.

**Comment by nelsonamaya82** [comment]
@allanaaa all the issues are fixed, except a few ones detailed below:

3. The style in the ToC block is intended to be different as it's a different kind of list, specific for this block, compared to the rest of lists (standard styling).

5. Initialy the top bar was hidden when there was no contact information (or when the contact info visibility option was set to the Footer only) but then after a review with the team, Sharon sugested to keep this top bar always visible. Anyway, when you scroll down, the top bar hides automatically so you cannot see the Advanced Search link again (unless you scroll up back), so it's important to have this link available in the search box:
[advanced-search.webm](https://github.com/omeka-s-themes/lively/assets/6953921/97b4d738-9d3c-4fb1-9990-3a821c1182a3)

8. The default behavior is that images flow past its container, however when the text in front of the image is equal or larger than the image height, the container has to adapt to the text, making the container larger than the image.

9. For cases where resource regions have 2 sidebars, I reduced the sidebars width by a 10% so the main region is now 60% wide while the sidebars are 20% each. When there's only one sidebar, the main region is 70% and the sidebar 30%.
The media query breakpoint is set at 1200px so yes, the layout is only visible on screens wider than 1200px (basically every desktop screen). A narrower screen would be a tablet or mobile device, so the sidebars and main region are stacked vertically.
The main container on this theme is 1440px, so all contents, regions, blocks, etc. are constrained to this width. So if the intention of a site is to use big graphics, I wouldn't use a 3-column layout but just a single sidebar and main region.

10. I think it doesn’t look good on narrow screens if we had the left sidebar and the main region in the same row, and then the right sidebar below them. However I tried this and having 2 columns first on narrow screens (below 1200px) makes the content look so tight. Anyway, resolutions between 1024px and 1200px are not so common. Most of devices are whether below 1024px (tablets in portrait mode and mobile devices) or above 1200px (tablets in landscape mode and desktop).

12. I couldn't find a way to add a description to the "Configure resource pages" page from the theme's config file, I think there isn’t an option to do that currently. I'll double check with John though.

**Comment by allanaaa** [comment]
I have a submission form page created by the Collecting module, where the margins around the fields seem to be missing: 

http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-third-site/page/submissions

Compare to the way the dotted border sits on the Advanced Search page:

http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-third-site/item/search

**Comment by allanaaa** [comment]
On this page, I'm getting the IIIF viewer exceeding the page width, as well as its own grid span setting:

http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-second-site/page/my-12-column-grid-page

There's a full-page-width one near the bottom of the page. 

There's actually two - one set up to "vertical" (expanding past the browser width) and one set to "horizontal" (that's very narrow). That one's behaving "correctly" because it's restricting itself to a 4-item grid, which ... you may not want? I would think 1, 2, or 3 media selected could take up flex space.

**Comment by nelsonamaya82** [comment]
@allanaaa the latest issues related to the Collecting module form and IIIF viewer were fixed and I pushed the code to the master branch. Could you retest and let me know if it works for you?

**Comment by allanaaa** [comment]
It's looking great!

You have a small problem with buttons on focus - some of them just go blank and don't return to visibility until you de-focus, which should probably be an on-hover action instead of on-focus:
<img width="584" alt="Screenshot 2024-10-04 at 15 04 57" src="https://github.com/user-attachments/assets/bf392f68-fa09-44c3-ace9-5765975e276e">
some 
<img width="558" alt="Screenshot 2024-10-04 at 15 05 02" src="https://github.com/user-attachments/assets/449b0d93-60eb-4941-9147-42f510aa7334">
<img width="867" alt="Screenshot 2024-10-04 at 15 01 47" src="https://github.com/user-attachments/assets/0b21a05e-6ed6-449a-8175-7a9117981746">

And not all of them have the same orange focus outline - which I'm not sure is an accessiblity thing, or if you just want to be consistent with that - I'll leave it up to you.

**Comment by allanaaa** [comment]
On Faceted Browse pages, we show the pagination information (Results "1-20 of 65", "page 1 of 4", with navigation arrows, etc.) at both the top and bottom of the results. 

<img width="1078" alt="Screenshot 2024-10-04 at 15 19 58" src="https://github.com/user-attachments/assets/6944dd10-5d9d-4979-bb86-08a1a5616f2f">


But in Lively, you opt to only show this pagination bar at the bottom of your item browse and item set browse pages. 

Do you wish to remove this for the Faceted Browse pages too, for consistency? Or add them to your theme's design? I personally like seeing the number of results right at the top of the screen, but it's up to you.

**Comment by allanaaa** [comment]
And, I'm sorry to say that we'll have a new page to throw at you - the Hierarchy module, which isn't released yet, will include these "Hierarchy" browse pages that will basically be search results with the hierarchy tree shown in the sidebar. 

http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-second-site/hierarchy/106

The thumbnails and item titles just need some styling on these pages. If it's the module that needs to send some formatting, [we can make an issue there instead](https://github.com/omeka-s-modules/Hierarchy/issues).

**Comment by nelsonamaya82** [comment]
@allanaaa all the issues reported here are fixed now:
- Buttons focus: it's fixed and now they don't dissappear. However the outline color seems to be a browser issue as I'm testing it on Chrome and it looks like this:
![image](https://github.com/user-attachments/assets/97ba32b0-6c8a-4de5-bcb9-81b9db05829e)
- Regarding pagination, I agree having it on both top and bottom so I added it to the bottom too.
- The styles were updated on the new Hierarchy page. It'd be great if the Hierarchy module rendered thumbnails as square images instead of medium size here (line 190): https://github.com/omeka-s-modules/Hierarchy/blob/v1.1.0/view/hierarchy/site/index/hierarchy.phtml#L190

**Comment by allanaaa** [comment]
> The styles were updated on the new Hierarchy page. It'd be great if the Hierarchy module rendered thumbnails as square images instead of medium size here (line 190): https://github.com/omeka-s-modules/Hierarchy/blob/v1.1.0/view/hierarchy/site/index/hierarchy.phtml#L190 

@matthewjmckinley I think this is yours to handle? I'd think the Hierarchy browse pages should just reflect whatever the theme does the rest of the time, including list/grid/toggle display settings and whatever derivative image the theme wants to pull, even if that's large. But the designers should make the call here. 

Here's a working hierarchy browse: http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-second-site/hierarchy/3
If you compare to http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-second-site/item that's pulling the large images even in the list view with tiny 100x100 display. 
And a faceted-browse page, in case that's helpful (the only other browse page with a sidebar like hierarchy): http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-second-site/faceted-browse/15

I think that's it for this issue - we can close this and make a new one for the Lively/Hierarchy interactions wherever that's most appropriate.

**Comment by nelsonamaya82** [comment]
@allanaaa the images size in the Hierarchy module work fine on Lively as I'm overriding the template, so I'm pulling the square version of them. However for other themes (including Freedom), it'd be great if we print the square images by default from the module for lists like the Hierarchy one as it's printing the medium size and doesn't look good as it prints them with the original ratio (portrait/landscape). Here's an example on Freedom:
![image](https://github.com/user-attachments/assets/5fad0740-a87a-4f91-8faa-26866f2d8626)

**Comment by allanaaa** [comment]
> @allanaaa the images size in the Hierarchy module work fine on Lively as I'm overriding the template, so I'm pulling the square version of them. However for other themes (including Freedom), it'd be great if we print the square images by default from the module for lists like the Hierarchy one as it's printing the medium size and doesn't look good as it prints them with the original ratio (portrait/landscape). 

Ah, my mistake. I'm now on the latest of Hierarchy and Freedom and mine looks like this:

<img width="1434" alt="Screenshot 2024-11-13 at 15 55 52" src="https://github.com/user-attachments/assets/7922c854-5520-48c6-91c2-e8351008ae18">

So, probably needs more work in the module and/or maybe in the theme. Either way, I think Lively's problems are taken care of.
